extends: relaxed

rules:
  line-length: disable
  indentation:
    indent-sequences: consistent
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    level: warning
  new-line-at-end-of-file:
    level: error
  trailing-spaces:
    level: error
