[mypy]
python_version = 3.12
ignore_missing_imports = False
warn_unused_ignores = True
disallow_untyped_defs = True

[mypy-xfuser.*]
ignore_missing_imports = True

[mypy-diffsynth.*]
ignore_missing_imports = True
