apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamwiseapp-service-account
  namespace: rtgen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streamwiseapp-manager
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/log", "services", "events", "namespaces", "clusterroles"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: streamwiseapp-manager-binding
subjects:
  - kind: ServiceAccount
    name: streamwiseapp-service-account
    namespace: rtgen
roleRef:
  kind: ClusterRole
  name: streamwiseapp-manager
  apiGroup: rbac.authorization.k8s.io
