apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamwise-service-account
  namespace: rtgen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streamwise-manager
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/log", "services", "events", "namespaces", "serviceaccounts", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: streamwise-manager-binding
subjects:
  - kind: ServiceAccount
    name: streamwise-service-account
    namespace: rtgen
roleRef:
  kind: ClusterRole
  name: streamwise-manager
  apiGroup: rbac.authorization.k8s.io
