replicaCount: 1

registry: abcd-xyz.azurecr.io

# tag coming from "services.json"
images:
  podcasttranscript:
    repository: podcasttranscript
    tag: XXXX
  kokoro:
    repository: kokoro
    tag: XXXX
  hunyuanframepack:
    repository: hunyuanframepack
    tag: XXXX
  hunyuanavatar:
    repository: hunyuanavatar
    tag: XXXX
  wan:
    repository: wan
    tag: XXXX
  fantasytalking:
    repository: fantasytalking
    tag: XXXX
  flux:
    repository: flux
    tag: XXXX
  fluxkontext:
    repository: fluxkontext
    tag: XXXX
  hidream:
    repository: hidream
    tag: XXXX
  bagel:
    repository: bagel
    tag: XXXX
  yolo:
    repository: yolo
    tag: XXXX
  imageresize:
    repository: imageresize
    tag: XXXX
  realesrgan:
    repository: realesrgan
    tag: XXXX
  gemma:
    repository: vllm/vllm-openai
    tag: XXXX
  llama32:
    repository: vllm/vllm-openai
    tag: XXXX

services:
  transcript:
    gpu: 0
    cpu: 2
    memory: 8Gi
    ephemeralStorage: 16Gi
  kokoro:
    gpu: 1
    cpu: 2
    memory: 8Gi
    ephemeralStorage: 16Gi
  hunyuanframepack:
    gpu: 2
    cpu: 24
    memory: 192Gi
    ephemeralStorage: 64Gi
  hunyuanavatar:
    gpu: 2
    cpu: 24
    memory: 192Gi
    ephemeralStorage: 64Gi
  wan:
    gpu: 1
    #gpu-type: a+ # TODO use this value
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 16Gi
  fantasytalking:
    gpu: 2
    cpu: 16
    memory: 256Gi
    ephemeralStorage: 16Gi
  flux:
    gpu: 2
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 64Gi
  fluxkontext:
    gpu: 1
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 64Gi
  hidream:
    gpu: 1
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 96Gi
  yolo:
    gpu: 1
    cpu: 8
    memory: 16Gi
    ephemeralStorage: 16Gi
  imageresize:
    gpu: 0
    cpu: 2
    memory: 8Gi
    ephemeralStorage: 16Gi
  realesrgan:
    gpu: 1
    cpu: 2
    memory: 8Gi
    ephemeralStorage: 16Gi
  bagel:
    gpu: 1
    cpu: 8
    memory: 192Gi
    ephemeralStorage: 64Gi
  gemma:
    gpu: 4
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 64Gi
    tensorParallel: 2
    model: google/gemma-3-27b-it
    guidedBackend: xgrammar
  llama32:
    gpu: 2
    cpu: 16
    memory: 192Gi
    ephemeralStorage: 128Gi
    tensorParallel: 2
    model: meta-llama/Llama-3.2-90B-Vision
    guidedBackend: xgrammar

hfTokenSecret: hf-token
hfHomeVolume: huggingface-cache
hfCacheStorage: 10Gi
